### ISSUE TITLE
link dictionary as resource

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arc-website#44]
I think the dictionary could become a useful resource to come back to on its own https://nfdi4plants.github.io/arc-website/dictionary/index and could be linked somewhere in the navbar

**Comment by kMutagene** [comment]
I'll link it in the new resources subpage

**Comment by Freymaurer** [comment]
> I'll link it in the new resources subpage

@kMutagene what is the state of this?

**Comment by kMutagene** [comment]
Not done yet

**Comment by kMutagene** [comment]
now linked in resources and navbar

**Comment by Brilator** [comment]
beautiful
