### ISSUE TITLE
navigation tree not working

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arc-website#57]
Links in nav tree on the left currently lead nowhere 

<img width="315" alt="Screenshot 2024-09-19 at 09 37 04" src="https://github.com/user-attachments/assets/d4055343-2d17-4c7d-bc58-40bbfb7625fd">

**Comment by Brilator** [comment]
@kMutagene ?

**Comment by Freymaurer** [comment]
We are working on it :)

**Comment by Freymaurer** [comment]
should be fixed!
