### ISSUE TITLE
links to dictionary dead 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arc-website#61]
Probably happened somewhere during redirection to own site? 

The dictionary links are adding a double slashes // 

See e.g. RDM here 
https://nfdi4plants.github.io/arc-website/details/resources/ linking to 
https://nfdi4plants.github.io/arc-website//dictionary/RDM

**Comment by Brilator** [comment]
Ok there's something else to it. It's not happening for all dictionary entries

**Comment by Freymaurer** [comment]
fix should be live in a few min 🙂
